[theme]
base = "light"
primaryColor = "#319795"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F9FF"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
port = 8501

[client]
toolbarMode = "minimal"
